# Generated by Django 5.2.7 on 2025-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
