# Generated by Django 5.2.7 on 2025-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_note_embedding_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('note', 'Note'), ('document', 'Document')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('note', 'Note'), ('document', 'Document')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('similarity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source_type', 'source_id', 'target_type', 'target_id')},
            },
        ),
    ]
